// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SonoBooking.Infrastructure.Context;

#nullable disable

namespace SonoBooking.Infrastructure.Migrations
{
    [DbContext(typeof(SonoBookingDbContext))]
    partial class SonoBookingDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("SonoBooking.Domain.Entities.Identity.RefreshToken", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.Property<string>("CreatedById")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("ExpiryTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(28)
                        .HasColumnType("nvarchar(28)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.Property<string>("ModifiedById")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.Property<string>("UserId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("SonoBooking.Domain.Entities.Identity.Role", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.Property<string>("CreatedById")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("GovernorateId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.Property<string>("ModifiedById")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("SonoBooking.Domain.Entities.Identity.User", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<DateOnly>("BirthDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.Property<string>("CreatedById")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("GovernorateId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsLogedIn")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.Property<string>("ModifiedById")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NationalId")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("nvarchar(14)");

                    b.Property<string>("NationalIdImage")
                        .IsRequired()
                        .HasMaxLength(140)
                        .HasColumnType("nvarchar(140)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("SonoTracker.Domain.Entities.Housing.Apartment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AllocationType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasDefaultValue("fixed");

                    b.Property<string>("ApartmentNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ApartmentType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("BuildingNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("DetailedAddress")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Floor")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("GenderType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasDefaultValue("male");

                    b.Property<string>("Governorate")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("available");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id")
                        .HasName("PK__Apartmen__3214EC0721231588");

                    b.HasIndex(new[] { "GenderType" }, "IDX_Apartments_GenderType");

                    b.HasIndex(new[] { "Status" }, "IDX_Apartments_Status");

                    b.HasIndex(new[] { "ApartmentNumber", "BuildingNumber", "Street", "City" }, "UX_Apartment_Number_Location")
                        .IsUnique();

                    b.ToTable("Apartments", "units");
                });

            modelBuilder.Entity("SonoTracker.Domain.Entities.Housing.Approval", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Decision")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("DecisionDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("LeaderId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("RequestId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Approval__3214EC0734F8A54C");

                    b.HasIndex("LeaderId");

                    b.HasIndex(new[] { "RequestId" }, "UX_Approvals_Request")
                        .IsUnique();

                    b.ToTable("Approvals", "booking");
                });

            modelBuilder.Entity("SonoTracker.Domain.Entities.Housing.Bed", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BedNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Dimensions")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int>("RoomId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("available");

                    b.HasKey("Id")
                        .HasName("PK__Beds__3214EC079A1B9CD4");

                    b.HasIndex(new[] { "RoomId" }, "IDX_Beds_RoomId");

                    b.HasIndex(new[] { "Status" }, "IDX_Beds_Status");

                    b.HasIndex(new[] { "RoomId", "BedNumber" }, "UX_Bed_Number_Per_Room")
                        .IsUnique();

                    b.ToTable("Beds", "units");
                });

            modelBuilder.Entity("SonoTracker.Domain.Entities.Housing.Companion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("BirthDate")
                        .HasColumnType("date");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("DocumentImageUrl")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("DocumentNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("birth_certificate");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("NationalId")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Relationship")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Companio__3214EC0728FDF18A");

                    b.HasIndex("UserId");

                    b.HasIndex(new[] { "NationalId" }, "UX_Companion_NationalId")
                        .IsUnique()
                        .HasFilter("([NationalId] IS NOT NULL)");

                    b.HasIndex(new[] { "DocumentNumber" }, "UX_Companions_DocumentNumber")
                        .IsUnique();

                    b.ToTable("Companions", "users");
                });

            modelBuilder.Entity("SonoTracker.Domain.Entities.Housing.Extension", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ApprovedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("NewEndDate")
                        .HasColumnType("date");

                    b.Property<int>("ReservationId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ReservationId");

                    b.ToTable("Extension");
                });

            modelBuilder.Entity("SonoTracker.Domain.Entities.Housing.Leader", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id")
                        .HasName("PK__Leaders__3214EC070064AA06");

                    b.HasIndex(new[] { "IsActive" }, "IDX_Leaders_IsActive");

                    b.HasIndex(new[] { "FullName", "Position" }, "UX_Leaders_Name_Position")
                        .IsUnique();

                    b.ToTable("Leaders", "booking");
                });

            modelBuilder.Entity("SonoTracker.Domain.Entities.Housing.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime?>("PaymentDate")
                        .HasColumnType("datetime");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("pending");

                    b.Property<int>("ReservationId")
                        .HasColumnType("int");

                    b.Property<string>("TransactionReference")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id")
                        .HasName("PK__Payments__3214EC0797960E75");

                    b.HasIndex(new[] { "ReservationId" }, "IDX_Payments_ReservationId");

                    b.HasIndex(new[] { "PaymentStatus" }, "IDX_Payments_Status");

                    b.ToTable("Payments", "booking");
                });

            modelBuilder.Entity("SonoTracker.Domain.Entities.Housing.Request", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("datetime");

                    b.Property<int?>("ApprovedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("RequestDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("RequestNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("pending");

                    b.HasKey("Id")
                        .HasName("PK__Requests__3214EC07B2D76077");

                    b.HasIndex("ApprovedBy");

                    b.HasIndex("CreatedBy");

                    b.HasIndex(new[] { "RequestNumber" }, "UX_Request_Number")
                        .IsUnique();

                    b.ToTable("Requests", "booking");
                });

            modelBuilder.Entity("SonoTracker.Domain.Entities.Housing.RequestParticipant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CompanionId")
                        .HasColumnType("int");

                    b.Property<int>("RequestId")
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__RequestP__3214EC07565E9385");

                    b.HasIndex("CompanionId");

                    b.HasIndex("UserId");

                    b.HasIndex(new[] { "RequestId" }, "IDX_RequestParticipants_RequestId");

                    b.ToTable("RequestParticipants", "booking");
                });

            modelBuilder.Entity("SonoTracker.Domain.Entities.Housing.RequestUnit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ApartmentId")
                        .HasColumnType("int");

                    b.Property<int?>("BedId")
                        .HasColumnType("int");

                    b.Property<int>("RequestId")
                        .HasColumnType("int");

                    b.Property<int?>("RoomId")
                        .HasColumnType("int");

                    b.Property<string>("UnitType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id")
                        .HasName("PK__RequestU__3214EC07A33A8588");

                    b.HasIndex("ApartmentId");

                    b.HasIndex("BedId");

                    b.HasIndex("RoomId");

                    b.HasIndex(new[] { "RequestId" }, "IDX_RequestUnits_RequestId");

                    b.ToTable("RequestUnits", "booking");
                });

            modelBuilder.Entity("SonoTracker.Domain.Entities.Housing.Reservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ActualCheckOutDate")
                        .HasColumnType("datetime");

                    b.Property<int?>("ApartmentId")
                        .HasColumnType("int");

                    b.Property<int?>("BedId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CheckInDate")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<int>("RequestId")
                        .HasColumnType("int");

                    b.Property<int?>("RoomId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("reserved");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("UnitType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Reservat__3214EC07909291A0");

                    b.HasIndex("ApartmentId");

                    b.HasIndex("BedId");

                    b.HasIndex("RoomId");

                    b.HasIndex(new[] { "StartDate", "EndDate" }, "IDX_Reservations_Dates");

                    b.HasIndex(new[] { "RequestId" }, "IDX_Reservations_RequestId");

                    b.HasIndex(new[] { "Status" }, "IDX_Reservations_Status");

                    b.HasIndex(new[] { "UserId" }, "IDX_Reservations_UserId");

                    b.ToTable("Reservations", "booking");
                });

            modelBuilder.Entity("SonoTracker.Domain.Entities.Housing.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ApartmentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("RoomNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("RoomType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("available");

                    b.HasKey("Id")
                        .HasName("PK__Rooms__3214EC07E6B4CB77");

                    b.HasIndex(new[] { "ApartmentId" }, "IDX_Rooms_ApartmentId");

                    b.HasIndex(new[] { "Status" }, "IDX_Rooms_Status");

                    b.HasIndex(new[] { "ApartmentId", "RoomNumber" }, "UX_Room_Number_Per_Apartment")
                        .IsUnique();

                    b.ToTable("Rooms", "units");
                });

            modelBuilder.Entity("SonoTracker.Domain.Entities.Housing.UnitImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ApartmentId")
                        .HasColumnType("int");

                    b.Property<int?>("BedId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("bit");

                    b.Property<int?>("RoomId")
                        .HasColumnType("int");

                    b.Property<string>("UnitType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id")
                        .HasName("PK__UnitImag__3214EC074E4C76EA");

                    b.HasIndex(new[] { "ApartmentId" }, "IDX_UnitImages_ApartmentId");

                    b.HasIndex(new[] { "BedId" }, "IDX_UnitImages_BedId");

                    b.HasIndex(new[] { "RoomId" }, "IDX_UnitImages_RoomId");

                    b.HasIndex(new[] { "UnitType", "ApartmentId", "RoomId", "BedId" }, "UX_UnitImages_Primary")
                        .IsUnique()
                        .HasFilter("([IsPrimary]=(1))");

                    b.HasIndex(new[] { "UnitType", "ApartmentId", "RoomId", "BedId", "ImageUrl" }, "UX_UnitImages_Unique")
                        .IsUnique()
                        .HasFilter("[UnitType] IS NOT NULL AND [ApartmentId] IS NOT NULL AND [RoomId] IS NOT NULL AND [BedId] IS NOT NULL AND [ImageUrl] IS NOT NULL");

                    b.ToTable("UnitImages", "units");
                });

            modelBuilder.Entity("SonoTracker.Domain.Entities.Housing.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("DocumentNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("national_id");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("NationalId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("NationalIdImageUrl")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id")
                        .HasName("PK__Users__3214EC072FE1513D");

                    b.HasIndex(new[] { "Email" }, "UQ__Users__A9D105344FCE9ED4")
                        .IsUnique()
                        .HasFilter("[Email] IS NOT NULL");

                    b.HasIndex(new[] { "NationalId" }, "UQ__Users__E9AA32FAFA94E5A9")
                        .IsUnique();

                    b.HasIndex(new[] { "DocumentNumber" }, "UX_Users_DocumentNumber")
                        .IsUnique();

                    b.ToTable("Users", "users");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("SonoBooking.Domain.Entities.Identity.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("SonoBooking.Domain.Entities.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("SonoBooking.Domain.Entities.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("SonoBooking.Domain.Entities.Identity.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SonoBooking.Domain.Entities.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("SonoBooking.Domain.Entities.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SonoBooking.Domain.Entities.Identity.RefreshToken", b =>
                {
                    b.HasOne("SonoBooking.Domain.Entities.Identity.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("User");
                });

            modelBuilder.Entity("SonoTracker.Domain.Entities.Housing.Approval", b =>
                {
                    b.HasOne("SonoTracker.Domain.Entities.Housing.Leader", "Leader")
                        .WithMany("Approvals")
                        .HasForeignKey("LeaderId")
                        .IsRequired()
                        .HasConstraintName("FK_Approvals_Leader");

                    b.HasOne("SonoTracker.Domain.Entities.Housing.Request", "Request")
                        .WithOne("Approval")
                        .HasForeignKey("SonoTracker.Domain.Entities.Housing.Approval", "RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Approvals_Request");

                    b.Navigation("Leader");

                    b.Navigation("Request");
                });

            modelBuilder.Entity("SonoTracker.Domain.Entities.Housing.Bed", b =>
                {
                    b.HasOne("SonoTracker.Domain.Entities.Housing.Room", "Room")
                        .WithMany("Beds")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Beds_Rooms");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("SonoTracker.Domain.Entities.Housing.Companion", b =>
                {
                    b.HasOne("SonoTracker.Domain.Entities.Housing.User", "User")
                        .WithMany("Companions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Companions_Users");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SonoTracker.Domain.Entities.Housing.Extension", b =>
                {
                    b.HasOne("SonoTracker.Domain.Entities.Housing.Reservation", "Reservation")
                        .WithMany("Extensions")
                        .HasForeignKey("ReservationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reservation");
                });

            modelBuilder.Entity("SonoTracker.Domain.Entities.Housing.Payment", b =>
                {
                    b.HasOne("SonoTracker.Domain.Entities.Housing.Reservation", "Reservation")
                        .WithMany("Payments")
                        .HasForeignKey("ReservationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Payments_Reservation");

                    b.Navigation("Reservation");
                });

            modelBuilder.Entity("SonoTracker.Domain.Entities.Housing.Request", b =>
                {
                    b.HasOne("SonoTracker.Domain.Entities.Housing.Leader", "ApprovedByNavigation")
                        .WithMany("Requests")
                        .HasForeignKey("ApprovedBy")
                        .HasConstraintName("FK_Requests_Leader");

                    b.HasOne("SonoTracker.Domain.Entities.Housing.User", "CreatedByNavigation")
                        .WithMany("Requests")
                        .HasForeignKey("CreatedBy")
                        .IsRequired()
                        .HasConstraintName("FK_Requests_User");

                    b.Navigation("ApprovedByNavigation");

                    b.Navigation("CreatedByNavigation");
                });

            modelBuilder.Entity("SonoTracker.Domain.Entities.Housing.RequestParticipant", b =>
                {
                    b.HasOne("SonoTracker.Domain.Entities.Housing.Companion", "Companion")
                        .WithMany("RequestParticipants")
                        .HasForeignKey("CompanionId")
                        .HasConstraintName("FK_RequestParticipants_Companion");

                    b.HasOne("SonoTracker.Domain.Entities.Housing.Request", "Request")
                        .WithMany("RequestParticipants")
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_RequestParticipants_Request");

                    b.HasOne("SonoTracker.Domain.Entities.Housing.User", "User")
                        .WithMany("RequestParticipants")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_RequestParticipants_User");

                    b.Navigation("Companion");

                    b.Navigation("Request");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SonoTracker.Domain.Entities.Housing.RequestUnit", b =>
                {
                    b.HasOne("SonoTracker.Domain.Entities.Housing.Apartment", "Apartment")
                        .WithMany("RequestUnits")
                        .HasForeignKey("ApartmentId")
                        .HasConstraintName("FK_RequestUnits_Apartment");

                    b.HasOne("SonoTracker.Domain.Entities.Housing.Bed", "Bed")
                        .WithMany("RequestUnits")
                        .HasForeignKey("BedId")
                        .HasConstraintName("FK_RequestUnits_Bed");

                    b.HasOne("SonoTracker.Domain.Entities.Housing.Request", "Request")
                        .WithMany("RequestUnits")
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_RequestUnits_Request");

                    b.HasOne("SonoTracker.Domain.Entities.Housing.Room", "Room")
                        .WithMany("RequestUnits")
                        .HasForeignKey("RoomId")
                        .HasConstraintName("FK_RequestUnits_Room");

                    b.Navigation("Apartment");

                    b.Navigation("Bed");

                    b.Navigation("Request");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("SonoTracker.Domain.Entities.Housing.Reservation", b =>
                {
                    b.HasOne("SonoTracker.Domain.Entities.Housing.Apartment", "Apartment")
                        .WithMany("Reservations")
                        .HasForeignKey("ApartmentId")
                        .HasConstraintName("FK_Reservations_Apartment");

                    b.HasOne("SonoTracker.Domain.Entities.Housing.Bed", "Bed")
                        .WithMany("Reservations")
                        .HasForeignKey("BedId")
                        .HasConstraintName("FK_Reservations_Bed");

                    b.HasOne("SonoTracker.Domain.Entities.Housing.Request", "Request")
                        .WithMany("Reservations")
                        .HasForeignKey("RequestId")
                        .IsRequired()
                        .HasConstraintName("FK_Reservations_Request");

                    b.HasOne("SonoTracker.Domain.Entities.Housing.Room", "Room")
                        .WithMany("Reservations")
                        .HasForeignKey("RoomId")
                        .HasConstraintName("FK_Reservations_Room");

                    b.HasOne("SonoTracker.Domain.Entities.Housing.User", "User")
                        .WithMany("Reservations")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_Reservations_User");

                    b.Navigation("Apartment");

                    b.Navigation("Bed");

                    b.Navigation("Request");

                    b.Navigation("Room");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SonoTracker.Domain.Entities.Housing.Room", b =>
                {
                    b.HasOne("SonoTracker.Domain.Entities.Housing.Apartment", "Apartment")
                        .WithMany("Rooms")
                        .HasForeignKey("ApartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Rooms_Apartments");

                    b.Navigation("Apartment");
                });

            modelBuilder.Entity("SonoTracker.Domain.Entities.Housing.UnitImage", b =>
                {
                    b.HasOne("SonoTracker.Domain.Entities.Housing.Apartment", "Apartment")
                        .WithMany("UnitImages")
                        .HasForeignKey("ApartmentId")
                        .HasConstraintName("FK_UnitImages_Apartment");

                    b.HasOne("SonoTracker.Domain.Entities.Housing.Bed", "Bed")
                        .WithMany("UnitImages")
                        .HasForeignKey("BedId")
                        .HasConstraintName("FK_UnitImages_Bed");

                    b.HasOne("SonoTracker.Domain.Entities.Housing.Room", "Room")
                        .WithMany("UnitImages")
                        .HasForeignKey("RoomId")
                        .HasConstraintName("FK_UnitImages_Room");

                    b.Navigation("Apartment");

                    b.Navigation("Bed");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("SonoBooking.Domain.Entities.Identity.User", b =>
                {
                    b.Navigation("RefreshTokens");
                });

            modelBuilder.Entity("SonoTracker.Domain.Entities.Housing.Apartment", b =>
                {
                    b.Navigation("RequestUnits");

                    b.Navigation("Reservations");

                    b.Navigation("Rooms");

                    b.Navigation("UnitImages");
                });

            modelBuilder.Entity("SonoTracker.Domain.Entities.Housing.Bed", b =>
                {
                    b.Navigation("RequestUnits");

                    b.Navigation("Reservations");

                    b.Navigation("UnitImages");
                });

            modelBuilder.Entity("SonoTracker.Domain.Entities.Housing.Companion", b =>
                {
                    b.Navigation("RequestParticipants");
                });

            modelBuilder.Entity("SonoTracker.Domain.Entities.Housing.Leader", b =>
                {
                    b.Navigation("Approvals");

                    b.Navigation("Requests");
                });

            modelBuilder.Entity("SonoTracker.Domain.Entities.Housing.Request", b =>
                {
                    b.Navigation("Approval");

                    b.Navigation("RequestParticipants");

                    b.Navigation("RequestUnits");

                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("SonoTracker.Domain.Entities.Housing.Reservation", b =>
                {
                    b.Navigation("Extensions");

                    b.Navigation("Payments");
                });

            modelBuilder.Entity("SonoTracker.Domain.Entities.Housing.Room", b =>
                {
                    b.Navigation("Beds");

                    b.Navigation("RequestUnits");

                    b.Navigation("Reservations");

                    b.Navigation("UnitImages");
                });

            modelBuilder.Entity("SonoTracker.Domain.Entities.Housing.User", b =>
                {
                    b.Navigation("Companions");

                    b.Navigation("RequestParticipants");

                    b.Navigation("Requests");

                    b.Navigation("Reservations");
                });
#pragma warning restore 612, 618
        }
    }
}
